name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: guuholivee
          outputs: |
            ./dist/github-contribution-grid-snake.svg

      - name: Commit the snake animation
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generated snake animation"
          add: "dist/*"

      - name: Push to 'output' branch
        run: |
          git fetch
          git switch --orphan output
          git rm -rf .
          cp -r dist/* .
          git add .
          git commit -m "Update snake"
          git push -f origin output
