name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate the snake
      uses: Platane/snk@v3
      with:
    github_user_name: guuholivee
    outputs: |
      dist/github-contribution-grid-snake.svg
    color_snake: "#00FF99" # verde neon
    color_dots: "#444444,#393939,#2e2e2e,#00FFC3,#00AA88"

      - name: Deploy to GitHub Pages (output branch)
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
